/*  THIS FILE WAS GENERATED BY THE TUXERA RELIANCE EDGE CONFIGURATION UTILITY.
    DO NOT MODIFY.

    Generated by configuration utility version 3.0
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 0U, 0U, 0U, false, 0U, 0U, "VOL0:" },
    { 0U, 0U, 0U, false, 0U, 0U, "VOL1:" },
    { 0U, 0U, 0U, false, 0U, 0U, "VOL2:" },
    { 0U, 0U, 0U, false, 0U, 0U, "VOL3:" },
    { 0U, 0U, 0U, false, 0U, 0U, "VOL4:" },
    { 0U, 0U, 0U, false, 0U, 0U, "VOL5:" },
};
